### ISSUE TITLE
DNC List Description

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#435]
- [ ] /workspaces/$id/dnc/all
- [ ] [Users should be able to DNC from disposition](https://github.com/chester-hill-solutions/callcaster/issues/431)
- [ ] [Managers should be able to then view every workspace DNC, what number it applies to, who did it, and from which campaign or interface](https://github.com/chester-hill-solutions/callcaster/issues/432)
- [ ] [Managers should also be able to manually add numbers to DNC list, and it defaults the origin to "manual](https://github.com/chester-hill-solutions/callcaster/issues/433)
- [ ] [shouldn't dial DNC marked numbers](https://github.com/chester-hill-solutions/callcaster/issues/434)
